# Generated by Django 4.2.11 on 2024-04-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('release_year', models.IntegerField()),
                ('song_count', models.IntegerField()),
                ('genre', models.CharField(max_length=300)),
            ],
        ),
    ]
