# Generated by Django 4.2.11 on 2024-04-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='genre',
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('genre', models.CharField(choices=[('Country', 'Country'), ('Pop', 'Pop'), ('Rap', 'Rap'), ('Alternative', 'Alternative')], default=('Country', 'Country'), max_length=200)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinyl')),
            ],
        ),
    ]
