# Generated by Django 4.2.11 on 2024-04-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_vinyl_genre_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchange', models.CharField(choices=[('Purchased', 'Purchased'), ('Returned', 'Returned'), ('Sold', 'Sold')], default='Purchased', max_length=200)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinyl')),
            ],
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
