# Generated by Django 4.2.11 on 2024-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_vinyl_song_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip Hop', 'Hip Hop'), ('Electronic', 'Electronic'), ('R&B', 'R&B'), ('Country', 'Country'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Blues', 'Blues'), ('Folk', 'Folk'), ('Indie', 'Indie'), ('Punk', 'Punk'), ('Soul', 'Soul'), ('Funk', 'Funk'), ('Disco', 'Disco'), ('Techno', 'Techno'), ('House', 'House'), ('Ambient', 'Ambient'), ('Gospel', 'Gospel'), ('Trap', 'Trap'), ('Dancehall', 'Dancehall'), ('Alternative', 'Alternative')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vinyl',
            name='genres',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
    ]
